version: '3.8'
services:
    mysql:
      container_name: mysql
#      hostname: test
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      volumes:
        - db:/var/lib/mysql
      ports:
        - "3306:3306"

    custom-redis:
      image: redis
      container_name: announcement-redis
      ports:
        - '6379:6379'
      volumes:
        - db:/data



    myapp:
     image: msann:v1
     ports:
       - '8090:8090'
#     networks:
#       - custom-network
     depends_on:
       - mysql
     environment:
       HOST : mysql
       PORT : 3306



volumes:
  db:
  dbp:

#networks:
#  custom-network: