spring:
  datasource:
    url: jdbc:mysql://localhost:3306/announcementApp?currentSchema=announcementApp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8090



