spring:
  datasource:
    url: jdbc:mysql://localhost:3306/announcementApp?currentSchema=announcementApp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


server:
  port: 8090


jwt:
  secret-key: ${SECRET_KEY:ms22DRMLGFJPGJPOGFKPOOGKIPOfddfhgbkivkkjsghkifgvxifgvgfiuFKGFPOKGPO}


